#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt update
sudo apt install -y nginx
if ! pgrep -x "nginx" > /dev/null; then
    # Start Nginx if it's not already running
    sudo nginx
else
    # Reload Nginx configuration to apply changes
    sudo nginx -s reload
fi
echo "Hello World!" | sudo tee /var/www/html/index.html

