#!/usr/bin/env bash
# Update the package list and install Nginx

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

sudo service nginx restart

