#!/usr/bin/env bash
#add custom HTTP response headers to the HTTP response of the web server.

# Create a custom Nginx configuration file for the custom header
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_headers.conf

# Reload Nginx to apply the new configuration
sudo systemctl reload nginx