#!/usr/bin/env bash
#add custom HTTP response headers to the HTTP response of the web server.

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Create a custom HTTP response header
echo 'X-Served-By: $hostname' | sudo tee /var/www/html/custom_header.html

# Reload Nginx to apply the new configuration
sudo systemctl reload nginx
