#!/bin/bash

count=1
while (( count <= 20 )); do
    case $count in
        4)
            echo "$count and then bad luck from China"
            ;;
        9)
            echo "$count and then bad luck from Japan"
            ;;
        17)
            echo "$count and then bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac

    (( count++ ))
done
